
# Site settings
title: "Kaixun Hua"
email: kaixun.hua@ubc.ca

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    
plugins:
  - jekyll-sitemap